### ISSUE TITLE
Add Qualys for image scanning

### ISSUE THREAD

**Issue by lgmorand** [Azure/sg-aks-workshop#15]
Once not in preview anymore, could be useful to add a small paragraph in Deploy App > Image Vulnerability Scanning and Management, to say that we have "embedded" image scanning within ACR.

If we quote every product on the market except "our" solution... :)

**Comment by kevingbb** [comment]
Agreed. The goal of this repo is to have recommendations around what is production ready today. We talk about future stuff in the Azure Security Center + AKS + ACR section in the thought leadership section.
