### ISSUE TITLE
AKS Falco audit rules not working

### ISSUE THREAD

**Issue by prakash1097** [Azure/sg-aks-workshop#17]
We have deployed the Falco k8s_audit_rules.yaml section as mentioned in the Cluster-config folder which is linked to Flux.
After the deployment, It seems only the falco_rules.yaml section is working. We were able to query the log results from Log analytics as well. 

These are some falco rules that are working.

- Log files were tampered	
- Shell history had been deleted or renamed	
- Privileged container started	
- Error File below / or /root opened for writing	
- Notice A shell was spawned in a container with an attached terminal	
- A shell configuration file has been modified	
- Docker or kubernetes client executed in container	
- Unexpected connection to K8s API Server from container

But for K8s-audit rules, the most important rules are as follows and they doesn't seem to be working.

1. Detect any attempt to create a namespace outside of a set of known namespaces
2. Detect any attempt to create a pod in the kube-system or kube-public namespaces
3. Detect any attempt to create a serviceaccount in the kube-system or kube-public namespaces
4. Detect any attempt to modify/delete a ClusterRole/Role starting with system
5. Detect any attempt to create a ClusterRoleBinding to the cluster-admin user
6. Detect any attempt to create a Role/ClusterRole with wildcard resources or verbs
7. Detect any attempt to create a Role/ClusterRole that can perform write-related actions
8. Detect any attempt to create a Role/ClusterRole that can exec to pods
9. Detect any attempt to create a deployment
10. Detect any attempt to delete a deployment
11. Detect any attempt to create a service
12. Detect any attempt to delete a service
13. Detect any attempt to create a configmap
14. Detect any attempt to delete a configmap
15. Detect any attempt to create a namespace
16. Detect any attempt to delete a namespace
17. Detect any attempt to create a service account
18. Detect any attempt to delete a service account
19. Detect any attempt to create a cluster role/role
20. Detect any attempt to delete a cluster role/role
21. Detect any attempt to create a clusterrolebinding
22. Detect any attempt to delete a clusterrolebinding

In the validate scenarios, 
https://github.com/Azure/sg-aks-workshop/tree/master/validate-scenarios
![image](https://user-images.githubusercontent.com/48716940/75113364-64c3c200-5673-11ea-9be8-1b660cbf76a5.png)

Here the rules validated are for falco rules but there isn't any description provided for audit rules.

**In the Falco documentation, it says to enable auditing policy for Master Node Kube API Server but in AKS since the users doesn't have access to Master Node, How does the Falco audit rules comes into action?**

**Comment by kevingbb** [comment]
There is a specific webhook config you need to do to setup the kube-audit logs. We have kept it simple and just leverage the falco rules.

**Comment by prakash1097** [comment]
Could you provide me some documentations with respect to AKS

**Comment by wadhahbenaissa** [comment]
@prakash1097 I am facing the same issue as yours.
I was wondering if it worked for you. If it's the case, would you please share your solution?

**Comment by kevingbb** [comment]
Hi @prakash1097 , I am not aware of a solution with AKS. The guidance I have been giving customers is to enable Azure Security Center on their cluster and it will perform security checks against the k8s audit logs, see here for more details:
https://docs.microsoft.com/en-us/azure/security-center/alerts-reference#alerts-akscluster

Another potential path I am aware of is the sysdiglabs aks-audit-log path which is for Sysdig Secure, but I have never personally tried it with just Falco:
https://github.com/sysdiglabs/aks-audit-log
