### ISSUE TITLE
Is it still work in progress?

### ISSUE THREAD

**Issue by nitinkhandelwal26** [Azure/sg-aks-workshop#26]

**Comment by kevingbb** [comment]
Hi @nitinkhandelwal26 , thanks for the interest in the repo. The concepts and content in the repo are still relevant, but keeping the technical content started to become a full-time job. Hence the WIP.

The core part of the content was moved into the Azure Architecture Center AKS Baseline Architecture. A more security-focused version of that baseline architecture is currently a work in progress.
