### ISSUE TITLE
Identify Personas to be included in scenario

### ISSUE THREAD

**Issue by yokimjd** [Azure/sg-aks-workshop#9]
Would be good to include the personas (dev, operations, networking, security, etc) in the roles that play a part in the Governance + Security Scenario

**Comment by kevingbb** [comment]
Great point. Here is a list to get things started, any major role missing?

- Security/Risk Lead (Required)
- Compliance Lead (Required)
- InfoSec Lead (Required)
- Identity & Access Mgmt Lead (Required)
- Networking Lead (Required)
- Cloud Engineering Lead (Required)
- Line of Business Owner (Required)

**Comment by lgmorand** [comment]
in which role do you put operations (monitoring/support), is it in "cloud engineering" ? or another one missing ?

**Comment by kevingbb** [comment]
The roles and responsibilities have been added to the customer scenario section under Areas of Responsibility.
